# Generated by Django 4.2.4 on 2023-08-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='Male', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('status', models.CharField(choices=[('stable', 'Stable'), ('improving', 'Improving'), ('critical', 'Critical')], max_length=20)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='A+', max_length=5)),
                ('height', models.PositiveIntegerField(default=170)),
                ('weight', models.PositiveIntegerField(default=100)),
                ('allergies', models.CharField(choices=[('Pollen', 'Pollen'), ('Dust Mites', 'Dust Mites'), ('Pet Dander', 'Pet Dander'), ('Mold', 'Mold'), ('Food Allergies', 'Food Allergies'), ('Insect Sting Allergies', 'Insect Sting Allergies'), ('Medication Allergies', 'Medication Allergies'), ('Latex Allergy', 'Latex Allergy'), ('Cockroach Allergy', 'Cockroach Allergy'), ('Other', 'Other')], default='Other', max_length=50)),
                ('diagnosis', models.CharField(choices=[('Hypertension (High Blood Pressure)', 'Hypertension (High Blood Pressure)'), ('Type 2 Diabetes', 'Type 2 Diabetes'), ('Asthma', 'Asthma'), ('Allergic Rhinitis', 'Allergic Rhinitis'), ('Migraine', 'Migraine'), ('Depression', 'Depression'), ('Anxiety Disorder', 'Anxiety Disorder'), ('Obesity', 'Obesity'), ('Chronic Obstructive Pulmonary Disease (COPD)', 'Chronic Obstructive Pulmonary Disease (COPD)'), ('Coronary Artery Disease', 'Coronary Artery Disease'), ('Hyperthyroidism', 'Hyperthyroidism'), ('Hypothyroidism', 'Hypothyroidism'), ('Gastroesophageal Reflux Disease (GERD)', 'Gastroesophageal Reflux Disease (GERD)'), ('Rheumatoid Arthritis', 'Rheumatoid Arthritis'), ('Osteoarthritis', 'Osteoarthritis'), ('Eczema', 'Eczema'), ('Psoriasis', 'Psoriasis'), ('Celiac Disease', 'Celiac Disease'), ('Irritable Bowel Syndrome (IBS)', 'Irritable Bowel Syndrome (IBS)'), ('Chronic Kidney Disease', 'Chronic Kidney Disease'), ('Stroke', 'Stroke'), ("Alzheimer's Disease", "Alzheimer's Disease"), ('Multiple Sclerosis', 'Multiple Sclerosis'), ('HIV/AIDS', 'HIV/AIDS'), ('Cancer', 'Cancer')], default='Hypertension', max_length=100)),
                ('doctor_id', models.PositiveIntegerField(default=1)),
                ('address', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(default='2003-04-20')),
            ],
        ),
    ]
