# Generated by Django 4.2.4 on 2023-08-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medi', '0006_alter_payment_consultation_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='medication',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='prescription',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='traitement',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
