# Generated by Django 4.2.4 on 2023-08-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password1', models.CharField(max_length=255)),
                ('password2', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=20)),
                ('speciality', models.CharField(max_length=255)),
            ],
        ),
    ]
