# Generated by Django 4.2.4 on 2023-08-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Username',
        ),
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
