# Generated by Django 4.2.4 on 2023-08-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Userprofile',
        ),
    ]
