# Generated by Django 4.2.4 on 2023-08-10 15:15

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='specialty',
            field=models.CharField(choices=[('General Practitioner (GP) or Family Medicine Physician', 'General Practitioner (GP) or Family Medicine Physician'), ('Pediatrician', 'Pediatrician'), ('Obstetrician/Gynecologist (OB/GYN)', 'Obstetrician/Gynecologist (OB/GYN)'), ('Dermatologist', 'Dermatologist'), ('Orthopedic Surgeon', 'Orthopedic Surgeon'), ('Cardiologist', 'Cardiologist'), ('Psychiatrist', 'Psychiatrist')], max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
