# Generated by Django 4.2.4 on 2023-08-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userprofile_email_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
