# Generated by Django 4.2.4 on 2023-08-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_doctor_bio_doctor_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(default='2001-04-20'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.TextField(default='MediClinic', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_hours',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
