# Generated by Django 4.2.4 on 2023-08-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_doctor_date_of_birth_doctor_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
